config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'main#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :users do
    collection do
      get    'new_password'
      patch  'update_password'
      patch  'create_expert'
    end
    resources :requests, only: [:new, :create]
    resources :conversations, only: [:show]
    resources :messages, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show]

  get 'new-expert', to: 'users#new_expert', as: "new_expert_users"

  get 'profile', to: 'users#profile', as: 'profile'
  get 'search',  to: 'search#index',  as: 'search'


end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  accepts_nested_attributes_for :messages

  default_scope {order(updated_at: "DESC")}

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  scope :active, -> {where('messages_count > ?',0)}

  def interlocutor(user)
    user == self.recipient ? self.sender : self.recipient
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  #before_filter :set_user, only: [:new,:create]
  load_and_authorize_resource

  def index
    @conversations = current_user.conversations.active.includes(:messages,:sender,:recipient).all
  end

  def show
    @conversation = current_user.conversations.active.includes(:messages,:sender,:recipient).find(params[:id])
    @interlocutor = @conversation.interlocutor(current_user)
    @messages     = @conversation.messages.all
  end
end

app/views/conversations/_conversation.slim
- interlocutor = conversation.interlocutor(current_user)
- last_message = conversation.messages.first
-if interlocutor.present? && last_message.present?
  .conversation-item
    .row.start-xs
      .col-xs-3
        =link_to user_path(interlocutor) , class: 'ex-contact' do 
          -if interlocutor.try(:avatar).blank?
            =image_tag "default-profile-img.png", class: "ex-avatar rounded"
          -else
            =image_tag interlocutor.avatar, class: "ex-avatar rounded"
          h3 #{interlocutor.fullname}
      .col-xs-2
        p.ex-default-label #{last_message.message_date}
      .col-xs-7
        p.dot-ellipsis.dot-height-120 #{nl2br(last_message.body)}
        =link_to "Open Chat",conversation_path(conversation)

app/views/conversations/index.slim
=render 'shared/header'
.container.main-cont
  .row.center-xs
    .col-xs-12.col-md-8.ex-card-box
      -if @conversations.count > 0
        .conversation-box
          = render @conversations
      -else
        h2 You have no messages yet

app/views/conversations/show.slim
=render 'shared/header'
.container.main-cont.chat
  .row.center-xs
    .col-xs-9
      .row.center-xs
        .col-xs-12.col-md-8.chat-header
          h2 #{@interlocutor.fullname}
      .row.end-xs
        .col-xs-2
          - if current_user.expert?
            .ex-contact style="text-align: left"
              -if current_user.avatar.blank?
                =image_tag "default-profile-img.png", class: "ex-avatar"
              -else
                =image_tag current_user.avatar, class: "ex-avatar"
        .col-xs-8
          =semantic_form_for(@message ||= Message.new, url: user_messages_path(@interlocutor), remote: true, :html => {class: "message-form", role: :form, 'data-model' => 'message',:'data-type' => 'json',:'data-user-id' => @interlocutor.id, :enctype => "multipart/form-data"}) do |f|
            =f.input :body, as: "text", input_html: {class: "form-control", rows: "5"}, label: false
            .row.end-xs
              .col-xs-5
                button.btn.btn-success type="submit" Send Message
      .messages-cont
        =render @messages

javascript:
  $('#message_body').val(message_store.getMessage(#{@interlocutor.id}))