config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'main#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :users do
    collection do
      get    'new_password'
      patch  'update_password'
      patch  'create_expert'
    end
    resources :requests, only: [:new, :create]
    resources :conversations, only: [:show]
    resources :messages, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show]

  get 'new-expert', to: 'users#new_expert', as: "new_expert_users"

  get 'profile', to: 'users#profile', as: 'profile'
  get 'search',  to: 'search#index',  as: 'search'


end

app/models/user.rb
class User < ActiveRecord::Base
  include ThinkingSphinx::Scopes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sent_requests, class_name: "Request", foreign_key: :user_id
  has_many :received_requests, class_name: "Request", foreign_key: :expert_id

  has_many :experts, through: :sent_requests
  has_many :users, through: :received_requests

  has_many :messages, dependent: :destroy

  validates :firstname, :lastname, :presence => true
  validates :email, length: { maximum: 255 }
  validates :firstname, :lastname, length: { maximum: 50 }
  validates :keywords, length: { maximum: 400 }
  validates :phone, length: { maximum: 20 }
  validates :cost,:rating, :numericality => {:allow_blank => true}

  validates :position,:description, :keywords, :presence => true, if: Proc.new {|u| u.expert?}

  as_enum :role, [:user, :expert],  source: :role,      map: :string

  mount_uploader :avatar, AvatarUploader

  before_create :set_defaults
  after_initialize :init

  after_save ThinkingSphinx::RealTime.callback_for(:user)
  process :cost, -> (val) {val.to_f.round(2)}

  scope :experts, -> {where(role: 'expert').order(created_at: "DESC")}
  scope :users,   -> {where(role: 'user')}

  sphinx_scope(:experts_search) {
    {:conditions => {role: 'expert'}}
  }

  attr_accessor :delta

  def conversations
    Conversation.where("sender_id = ? OR recipient_id = ?", self.id, self.id)
  end

  def set_defaults
    self.role = :user
  end

  def init
    self.cost = nil if self.cost == 0.0
  end

  def fullname
    [firstname, lastname].compact.reject(&:blank?).join(' ')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource param_method: :password_params

  def index
  end

  def show
    @user = get_user    
  end

  def profile
    @user = current_user
    render 'show'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(user_params)
        flash[:notice] = "Profile successfully updated"
        format.html { redirect_to profile_path }
        format.json { render json: { location: profile_path}, status: 200 }
      else
        format.html { render 'edit'}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_password
   @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    respond_to do |format|
      if password_params[:password].blank? && password_params[:password_confirmation].blank?
        @user.errors.add(:password, "New password must be at least 8 characters")
        format.html { render 'new_password' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      elsif @user.update_with_password(password_params)
        sign_in @user, :bypass => true
        flash[:notice] = "Your password has been changed"
        format.html {redirect_to profile_path}
        format.json { render json: { location: root_path}, status: 200 }
      else
        format.html { render 'new_password' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_expert
    if !user_signed_in?
      redirect_to new_user_registration_path, flash: {notice: "Sign up or login to create your expert profile"}
    end
    @user = current_user
  end

  def create_expert
    @user = User.find(current_user.id)
    @user.role = :expert
    respond_to do |format|
      if @user.update_attributes(user_params)
        flash[:notice] = "Expert Profile successfully created"
        format.html { redirect_to profile_path }
        format.json { render json: { location: profile_path}, status: 200 }
      else
        format.html { render 'new_expert'}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def get_user
      if !params[:id]
        current_user
      else
        User.find(params[:id])
      end
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation, :current_password)
    end

    def user_params
      params.require(:user).permit(:firstname, :lastname, :avatar, :keywords, :position, :description, :rating, :cost, :phone, :availability, :timezone,:delta)
    end

    private
      def not_authorized
        redirect_to root_url, alert: "Unauthorized Access"
      end
end

app/views/users/_user.slim
.col-xs-12.col-sm-6.col-md-4
  .ex-card-box.card-profile
    .row.card-profile-title
      = link_to user_path(user) do
        .col-xs-4
          -if user.avatar.blank?
            =image_tag "default-profile-img.png", class: "ex-avatar"
          -else
            =image_tag user.avatar, class: "ex-avatar"
        .col-xs-8.card-profile-name-cont
          h3.card-profile-name #{user.fullname}
          .ex-italic-label #{placeholder_if_empty(user.position, "Current Role")}
          //div.ex-badge.ex-cost-badge Cost per 30min:
    .row
      .col-xs-12
        .ex-rating-bar
          p
            |Rating
            span.text-success.pull-right 93%
          .progress.progress-success
            .progress-bar aria-valuemax="100" aria-valuemin="0" aria-valuenow="93" role="progressbar" style=("width: 93%;")
    .row.card-profile-body
      .col-xs-12
          p #{user.keywords}

app/views/users/edit.slim
=render 'shared/header'
.container.main-cont
  .row.center-xs
    .col-xs-12.col-md-12.col-lg-9.ex-card-box.full-profile
      =render "users/#{@user.role}/form", user: @user

app/views/users/new_expert.slim
=render 'shared/header'
.container.main-cont
  .row.center-xs
    .col-xs-12.col-md-12.col-lg-9.ex-card-box.full-profile
      =semantic_form_for(@user, url: create_expert_users_path, html: {class: "no-json-form expert-form"}) do |f|
        .row.start-xs
          .col-xs-12.col-sm-4
            .full-profile-avatar-box
              .ex-avatar-placeholder style="#{'background-image: url('+image_url(@user.avatar_url)+')'}"
                h2 Add a photo
                = f.input :avatar, label: false, input_html: {accept: "image/*"}
                -if @user.avatar.blank?
                  =image_tag "default-profile-img.png", class: "ex-avatar"
                -else
                  =image_tag @user.avatar, class: "ex-avatar"

          .col-xs-12.col-sm-8.full-profile-description
            .full-profile-header-box
              = f.input :firstname, input_html: {class: "ex-live-field"}, label: "First name"
              = f.input :lastname, input_html: {class: "ex-live-field"}, label: "Last name"
            .ex-italic-label
              = f.input :position, input_html: {class: "ex-live-field"}, label: "Current Role"
            .ex-italic-label
              = f.input :phone, input_html: {class: "ex-live-field"}, label: "Phone"

              .ex-circle-meta
                | 9.3
                .ex-circle-meta-label rating

            .full-profile-box
              h3 Key expertise:
              p
                =f.input :keywords, as: "text", input_html: {class: "ex-live-field", rows: 4, style: "min-width: 80%;"}, label: false

            .full-profile-box
              h3 About me:
              p
                =f.input :description, as: "text", input_html: {class: "ex-live-field", rows: 6, style: "min-width: 80%;"}, label: false
            .full-profile-submit-button
              button.btn.btn-success.default type="submit" Update Profile

app/views/users/new_password.slim
=render 'shared/header'
.ex-background.account-pages
.auth-wrapper
  = render 'devise/form_header'
  .ex-card-box.strong-shadow
    .text-center
      h4.text-uppercase.form-header Change Password
    =semantic_form_for(@user, url: update_password_users_path, html: {class: "no-json-form"}) do |f|
      =f.input :current_password, input_html: {class: "form-control", placeholder: "Current Password"}, label: false
      =f.input :password, input_html: {class: "form-control", placeholder: "New Password"}, label: false
      =f.input :password_confirmation, input_html: {class: "form-control", placeholder: "Password Confirmation"}, label: false
      .text-center
        button.btn.btn-primary type="submit" Update
  .text-center
    h5.text-muted
      | Forgot your password?
      =link_to " Reset Password", new_user_password_path

app/views/users/show.slim
=render 'shared/header'
.container.main-cont
  .row.center-xs
    .col-xs-12.col-sm-12.col-md-9
      =render "users/#{@user.role}/full_profile", user: @user
    .col-xs-12.col-sm-12.col-md-3
      .profile-sidebar
        .ex-buttons-group
          - if can?(:create, Message) && @user.expert? && !current_user.expert?
            = link_to 'Message Expert',new_user_message_path(@user), class: "btn btn-success modal-trigger", data: {:'target-id' => 'message-form'}
          - if !user_signed_in?
            = link_to 'Message Expert',new_user_message_path(@user), class: "btn btn-success"
          - if can? :update, @user
            =link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-success"
          - if can?(:new, Request) && @user.expert?
            =link_to 'Book Expert', new_user_request_path(@user), class: "btn btn-success"