config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'main#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :users do
    collection do
      get    'new_password'
      patch  'update_password'
      patch  'create_expert'
    end
    resources :requests, only: [:new, :create]
    resources :conversations, only: [:show]
    resources :messages, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show]

  get 'new-expert', to: 'users#new_expert', as: "new_expert_users"

  get 'profile', to: 'users#profile', as: 'profile'
  get 'search',  to: 'search#index',  as: 'search'


end

app/views/shared/_header.html.slim
header
  .container
    .ex-logo
      =link_to root_path do
        | Expert
        span verse
    ul.ex-horizontal-nav
      - if !user_signed_in?
        li
          =link_to new_user_session_path, class: "ex-main-link"
            | Sign In
        li
          =link_to new_user_registration_path, class: "ex-main-link"
            | Sign Up
      -else
        li
          =link_to conversations_path, class: "ex-main-link"
            | Messages
        li.dropdown
          a.dropdown-toggle href="#" data-toggle="dropdown"
            .ex-widget-user
              - if current_user.avatar.blank?
                = image_tag 'default-profile-img.png', class: 'ex-img-circle'
              -else
                = image_tag current_user.avatar, class: 'ex-img-circle'
              | #{current_user.firstname}
          ul.dropdown-menu
            li
              =link_to 'Profile', profile_path, class: "ex-main-link"
            li
              =link_to 'Edit Profile', edit_user_path(current_user), class: "ex-main-link"
            li
              =link_to 'Change Password', new_password_users_path, class: "ex-main-link"
            li
              =link_to 'Logout', destroy_user_session_path, method: :delete, class: "ex-main-link"


= flash_messages